spring:
  application:
    name: jwe-generator
  datasource:
    url: jdbc:postgresql://postgres-db:5432/medinapv1994_db
    username: admin
    password: admin

server:
  port: 8081

jwe:
  certificate:
    filename: pkcs12Certificate.p12
    alias: alias
    pwd: pkcs12pwd
  signingkey:
    filename: private_key.der
  verifierkey:
    filename: public_key.der