configuration:
  environment: dev

spring:
  application:
    name: jwe-generator
  datasource:
    url: jdbc:postgresql://postgres-db:5432/medinapv1994_db
    username: admin
    password: admin
  profiles:
    active: dev
  config:
    import: 'optional:configserver:http://localhost:8088'

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

logging:
  level:
    org:
      hibernate: debug

jwe:
  certificate:
    filename: pkcs12Certificate.p12
    alias: alias
    pwd: pkcs12pwd
  signingkey:
    filename: private_key.der
  verifierkey:
    filename: public_key.der