spring:
  application:
    name: oauth-server

server:
  port: 8080

oauth:
  jwt:
    key: jwt-signature-key-tfg-vmp
  client:
    frontend:
      name: frontend
      pwd: 12345
    payment:
      name: payment-service
      pwd: 12345