configuration:
  environment: dev

spring:
  application:
    name: oauth-server
  config:
    import: 'optional:configserver:http://config-server:8888'

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

oauth:
  jwt:
    key: jwt-signature-key-tfg-vmp
  client:
    frontend:
      name: frontend
      pwd: 12345
    payment:
      name: payment-service
      pwd: 12345