configuration:
  environment: default

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/tfg
    username: admin
    password: admin
  config:
    import: 'optional:configserver:http://config-server:8888'

server:
  port: 8091

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

logging:
  level:
    org:
      hibernate: debug

jwe:
  certificate:
    filename: pkcs12Certificate.p12
    alias: alias
    pwd: pkcs12pwd
  verifierkey:
    filename: public_key.der