spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://postgres-db:5432/medinapv1994_db
    username: admin
    password: admin

server:
  port: 8091

jwe:
  certificate:
    filename: pkcs12Certificate.p12
    alias: alias
    pwd: pkcs12pwd
  verifierkey:
    filename: public_key.der